### ISSUE TITLE
Automatic Capacity Management returns 404

### ISSUE THREAD

**Issue by fritntap** [NetAppDocs/bluexp-fsx-ontap#58]
### Page URL

https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html

### Page title

Set up permissions for FSx for ONTAP

### Summary

Hi, when clicking on the automatic capacity management hyperlink on this page, the requested page returns a 404 page not found. This hyperlink is located under the Set up the IAM role > Steps section of the page.

Thank you.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@fritntap thank you for catching this! I couldn't quite figure out why it was breaking, but I reset it and it will work now. This ticket will auto-close when I merge the change, but it will take a few minutes for the change to be live. Feel free to reply to this comment even after it closes. 

Many thanks!
