### ISSUE TITLE
Requesting removal of resizing from FSx BXP documentation

### ISSUE THREAD

**Issue by ptwsnd** [NetAppDocs/bluexp-fsx-ontap#60]
### Page URL

https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-manage-fsx-volumes.html

### Page title

Manage volumes for Amazon FSx for NetApp ONTAP

### Summary

There is currently no resizing modification allowed in BXP for FSx volumes.
Unlike FSx, BXP allows CVO vol size modification from Advanced View setting. 

Requesting to change this line:
`For NFS, you can modify  and tags.`
to:
`For NFS, you can modify tags.`

Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@ptwsnd per our email, I'm taking ownership of this. Thanks!

**Comment by juliantap** [comment]
@ptwsnd I ended up removing the bullets for NFS & CIFS. I don't think they really added any value. Also, the NFS bullet referred to editing vol tags from `Edit volume settings`, which was no longer correct. I added a note to `Manage volume tags` to clarify the wait time for AWS sync. 

This issue auto-closed when I merged the change, but if you have additional comments or questions in this issue, you can still comment here. 

Thank you for contributing to the quality of our docs!
