### ISSUE TITLE
Missing a comma in the JSON example

### ISSUE THREAD

**Issue by olivernowak20** [NetAppDocs/bluexp-fsx-ontap#65]
### Page URL

https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html

### Page title

Set up permissions for FSx for ONTAP

### Summary

Under "Setup the IAM Role", step 2 "Create a policy", there is a comma missing at the end of this line under the "Security groups" tab:

"ec2:DeleteSecurityGroup"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@olivernowak20 thank you for catching this and contributing to the quality of our docs! The change is getting ready to merge now.
