### ISSUE TITLE
Need to include the option of using External ID 

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/bluexp-fsx-ontap#67]
### Page URL

https://docs.netapp.com/us-en/bluexp-fsx-ontap/requirements/task-setting-up-permissions-fsx.html

### Page title

Set up permissions for FSx for ONTAP

### Summary

AWS recommends using an external ID:
_We recommend using an external ID in multi-tenant situations. For details, see [How to use an external ID when granting access to your AWS resources to a third party](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.aws.amazon.com%2FIAM%2Flatest%2FUserGuide%2Fid_roles_create_for-user_externalid.html&data=05%7C01%7CRichard.Nicholl%40netapp.com%7Cc356746aaaa741091a1908dbcf5a7737%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638331759674833665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PHeAfZDyzG1ZcmiaoIRmWqr0OGd6%2F%2BI6GTUPd3Uc%2Bfw%3D&reserved=0)._

It is in our BlueXP UI as an option:

![image](https://github.com/NetAppDocs/bluexp-fsx-ontap/assets/519212/6b81f6b2-9554-43a1-a3cb-2cbbf741f4e4)

And they would simply set this external ID on AWS side when creating the role
![image](https://github.com/NetAppDocs/bluexp-fsx-ontap/assets/519212/93436658-5272-404b-abd8-88e661dd5713)

I think we should include it since customers may not be aware that we support it if it is not called out in the docs.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thank you, @nichollri! I've added content to recommend specifying an external ID. The changes are merging shortly.
