### ISSUE TITLE
Add note on FSx for NetApp ONTAP supporting S3 protocol

### ISSUE THREAD

**Issue by jshoucair** [NetAppDocs/bluexp-fsx-ontap#74]
### Page URL

https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html

### Page title

Learn about Amazon FSx for NetApp ONTAP

### Summary

Beginning in ONTAP 9.11+, FSx for NetApp ONTAP also supports ONTAP S3 as well as Multiprotocol NAS volumes (CIFS/NFS with S3 access) in addition to CIFS/SMB, NFS, and iSCSI.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@jshoucair, thank you for submitting this feedback. I'll work on the update and let you know when it's complete.
